-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    category_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.menu_items
(
    id integer NOT NULL DEFAULT nextval('menu_items_item_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric NOT NULL,
    category_id integer NOT NULL,
    restaurant_id integer NOT NULL,
    CONSTRAINT menu_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.restaurants
(
    restaurant_id integer NOT NULL DEFAULT nextval('restaurants_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT restaurants_pkey PRIMARY KEY (restaurant_id)
);

CREATE TABLE IF NOT EXISTS public.restaurant_category
(
    id serial NOT NULL,
    category_id integer,
    restaurant_id integer,
    CONSTRAINT restaurant_category_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.menu_items
    ADD CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.menu_items
    ADD CONSTRAINT menu_items_restaurant_id_fkey FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurants (restaurant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.restaurant_category
    ADD CONSTRAINT restaurant_category_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.restaurant_category
    ADD CONSTRAINT restaurant_category_restaurant_id_fkey FOREIGN KEY (restaurant_id)
    REFERENCES public.restaurants (restaurant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;